### ISSUE TITLE
Not working in Ubuntu 20.04 and GNOME 3.36.4

### ISSUE THREAD

**Issue by LastStarDust** [lunaryorn/jetbrains-search-provider#12] opened 2020-12-13 01:43 UTC
Hello!
I would like to use this extension but I cannot get it to work.
Here is my setup:

- Ubuntu 20.04
- GNOME 3.36.4
- CLion 2020.3 installed via snap
- PyCharm Professional Edition 2020.3 installed via snap
- jetbrains-search-provider v11 installed via GNOME extensions website

If I try to search a project by name it does not come up. How can I help you debug this issue? Is there a log file somewhere that I can look at?
Thank you

**Comment by lunaryorn** [comment] 2020-12-13 07:18
`journalctl --user` will give you all log messages of your user session, including this from gnome shell and this extension.

Other than that you're on your own.  I'm sorry, but this extension works for me, and I do not have the time to debug this issue.

**Comment by lunaryorn** [comment] 2020-12-14 15:51
I'll close this issue because I won't do anything about it now.  Please do re-open if you have identified the cause and would like to propose a fix in this extension.

**Closed by lunaryorn** 2020-12-14 15:51 UTC

**Comment by LastStarDust** [comment] 2021-02-03 06:22
Fixed in the latest version
